// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int greater = 0, lessOrEqual = 0;
		for (int i = 0; i < N; i++) {
			double randomNumber = Math.random();
			if (randomNumber > 0.5) {
				greater++;
			}
			else {
				lessOrEqual++;
			}
			i++;
		}
		System.out.println("> 0.5:  " + greater + " times");
		System.out.println("<= 0.5: " + lessOrEqual + " times");
		if (lessOrEqual > 0) {
			double ratio = (double) greater / lessOrEqual;
			System.out.println("Ration: " + ratio);
		}
	}
}
